version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bee_db
      MYSQL_USER: bee
      MYSQL_PASSWORD: bee123
    ports:
      - "3306:3306"
    networks:
      - bee_net

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:rootpassword@db/bee_db
    networks:
      - bee_net

networks:
  bee_net:
    driver: bridge
